### ISSUE TITLE
chla_dineof <- sinkr::dineof(chla, delta.rms = DINEOF_PRECISION)  

### ISSUE THREAD

**Issue by joinbao** [marchtaylor/sinkr#10]
When running this line of code, a warning appears:
Warning messages:
1: In rm(list = c("Xa.best", "n.eof.best", "SVDi", "RECi")) :
  object 'SVDi' not found
2: In rm(list = c("Xa.best", "n.eof.best", "SVDi", "RECi")) :
  object 'RECi' not found

Does anyone have any idea? 
Thanks

**Comment by marchtaylor** [comment]
Thanks for your feedback. Could you provide a reproducible example of the error?
