### ISSUE TITLE
getting negative values of eof over high rainfall zones

### ISSUE THREAD

**Issue by javakh** [marchtaylor/sinkr#4]
I'm doing EOF analysis over India using 'eof' function of your package.But I have obtained negative values of eof over high rainfall zones which is contradictory.
![wpi-future-eof](https://cloud.githubusercontent.com/assets/11016843/12911363/1163f07e-cf38-11e5-838f-7cdb7313745b.png)
In this figure you can see the red coloured zones in the western part which indicates lower eof values than other areas. But the western region (western ghat mountains of India)receives much higher rainfall than other areas. So,the picture should be opposite.

So, what's the problem in this function and how to solve it.

Thanks.

**Comment by marchtaylor** [comment]
These EOF values ($u) need to be multiplied by their respective principle components ($A) to derive the value. The sign will also depend on whether you have centered your data, thus you may be looking at anomalies from the mean. My guess is that you are using "centered=FALSE", and thus EOF1 and PC1 is probably describing a mean. PC1 is probably fully negative.
