### ISSUE TITLE
installing dependencies when default directory not writable

### ISSUE THREAD

**Issue by agilly** [marchtaylor/sinkr#7]
On certain R installations it may happen that the default R directory for libraries is not writable. In this case it would be helpful to ask if the user wants to specify another directory when installing dependencies.

For example when installing dependencies `irgba` and `Rcpp`:
```
Installing Rcpp
'/software/R-3.2.2/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpCq7JLQ/devtools51753aa0ad41/Rcpp'  \
  --library='/write/protected/path/' --install-tests

Error: ERROR: no permission to install to directory '/write/protected/path/'
```

Currently the dependencies have to be added manually:

```
>install.packages("Rcpp")
Installing package into ‘/write/protected/path/’
(as ‘lib’ is unspecified)
Warning in install.packages("Rcpp") :
  'lib = "/write/protected/path/"' is not writable
Would you like to use a personal library instead?  (y/n) y
```

**Comment by marchtaylor** [comment]
You may be able to add further arguments to install_github.  I'm not sure this is something that can be incorporated into the package itself. Please feel free to correct me if you know otherwise.

**Comment by agilly** [comment]
You're right, the `lib=` argument can be passed to `install_github` which will pass it to `install_packages`. Alternatively, setting `R_LIBS` to the desired location before calling R works as well.
