### ISSUE TITLE
Question regarding bootstraping SVD

### ISSUE THREAD

**Issue by eliocamp** [marchtaylor/sinkr#8]
Hey! I'm trying to get bootstrap CI for EOFs and I'm looking at your code. I see that you sample the rows of the data, why is that? I'm trying to understand what would be the difference between sampling rows or columns. 

Thanks!

**Comment by marchtaylor** [comment]
Hello. Sorry, I hadn't seen your comment until now. The logic behind sampling the rows is that EOF is based on the covariances among the columns, thus the resampling does not affect this dimension, and you will always be comparing a decomposition of the same sized covariance matrix.
